Feature/list published pagecontent if versioning enabled
nephila/djangocms-page-sitemap pull request #61
Opened 2020-11-04 19:29 UTC by NarenderRajuB

Add filter to list only published page contents if versioning is enabled

2020-11-04 20:12 UTC, Aiky30 commented on djangocms_page_sitemap/sitemap.py
> +                page_content = PageContent.objects.filter(
This is really bad for performance. I think we need to query better in the first place.

2020-11-11 11:41 UTC, Aiky30 commented on djangocms_page_sitemap/sitemap.py
>              .filter(language__in=languages, path__isnull=False, page__login_required=False)
We need to prefetch page__page_content, then in the url loop below (for page_url in all_urls:) we can exclude any urls that don't have a page_content entry.

2020-11-11 11:43 UTC, Aiky30 commented on djangocms_page_sitemap/sitemap.py
Maybe something like: if not page_url.page.page_content_count: continue

2020-11-16 21:34 UTC, Aiky30 requested changes

2020-11-16 21:34 UTC, Aiky30 commented on tests/test_sitemap.py
> +            page1_content = create_title(title='pagecontent1', language='en', page=page1,
get_pages already creates the page contents. I would advise doing the publishing in one place i.e. get_pages, this is how it used ot work: https://github.com/nephila/djangocms-page-sitemap/blob/develop/tests/base.py#L37

2020-11-17 14:08 UTC, Aiky30 requested changes

2020-11-17 14:08 UTC, Aiky30 commented on djangocms_page_sitemap/sitemap.py
> +            language__in=languages
I'm thinking that we can add  `page__pagesitemapproperties__include_in_sitemap=True` here now as we are using the prefetch query.

We then no longer need the exclusion filtering below.

We would need to do a count and prove this logic.

2020-11-17 14:08 UTC, Aiky30 commented on djangocms_page_sitemap/sitemap.py
> +        page_content_prefetch= Prefetch(
```suggestion
        page_content_prefetch = Prefetch(
```

2020-11-17 14:27 UTC, Aiky30 commented on djangocms_page_sitemap/sitemap.py
> +            published_page_content = False
```python
            has_page_content = False
            for page_content in page_url.page.pagecontent_set.all():
                if page_url.language == page_content.language:
                    has_page_content = True
            if has_page_content:
                valid_urls.append(page_url)
```

2020-11-19 11:12 UTC, Aiky30 approved these changes

2020-11-19 11:14 UTC, Aiky30 commented
@yakky We found that we were outputting draft pages in the sitemap, there appeared to be a large performance hit in the previous implementation of fetching the items, both are fixed with the changes in this PR.

2020-11-20 00:21 UTC, yakky approved these changes

2020-11-20 00:21 UTC, merged