feat: Backport cms 4.0.x - Django 3.2 with Python 3.8 & 3.9 support, including update tooling
nephila/djangocms-page-sitemap pull request #77
Opened 2022-08-27 17:31 UTC by yakky

# Description

Merge code from #70 with updated develop

## References

Fix #70 

# Checklist

* [x] I have read the [contribution guide](https://djangocms-page-sitemap.readthedocs.io/en/latest/contributing.html)
* [x] Code lint checked via `inv lint`
* [x] ``changes`` file included (see [docs](https://djangocms-page-sitemap.readthedocs.io/en/latest/contributing.html#pull-request-guidelines))
* [x] Usage documentation added in case of new features
* [x] Tests added

2022-08-27 17:39 UTC, yakky commented
@Aiky30 can you review this port of #70? I have merged with latest update from develop to make sure the two branches don't drift apart

I'll make a release to divio cloud with the current state of this branch and a beta one after merge

2022-09-01 08:22 UTC, Aiky30 requested changes
Looks good, the only minor thing is the pinning of djangocms-verisoning. I updated the authors file but that could be auto populated so may undo any changes. 

Also, great to have you back around @yakky, we genuinely missed you man.

2022-09-01 08:22 UTC, Aiky30 commented on AUTHORS.rst
>  * Anton Egorov
Not sure if this is auto populated. 
```suggestion
* Aiky30
* Anton Egorov
```

2022-09-01 08:22 UTC, Aiky30 commented on requirements-test.txt
> +https://github.com/Aiky30/djangocms-versioning/tarball/feature/django-32-compat#egg=djangocms-versioning
```suggestion
https://github.com/django-cms/djangocms-versioning/tarball/master#egg=djangocms-versioning
```

This was an old pin before 3.2 changes were merged.

2023-05-12 21:42 UTC, yakky commented
Replaced by #83 which includes the whole set of django CMS 4 changes

2023-05-12 21:42 UTC, closed without merging